INSERT INTO Materie (Nome) VALUES
('Tecnologie Informatiche'),
('Chimica'),
('Matematica'),
('Fisica'),
('Disegno'),
('Lettere'),
('Inglese'),
('Geografia'),
('Scienze'),
('Diritto'),
('STA (Automazione)'),
('STA (Informatica)'),
('STA (Chimica)'),
('TP-SIT'),
('TPSE'),
('Informatica'),
('Elettronica'),
('Telecomunicazioni'),
('Sistemi e Reti'); 
